# Generated by Django 5.2.6 on 2025-09-26 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('insem', 'In-Semester'), ('endsem', 'End-Semester')], max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('pdf_file', models.FileField(upload_to='papers/pdfs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='university.subject')),
            ],
            options={
                'ordering': ['year', 'exam_type'],
            },
        ),
    ]
