# Generated by Django 5.2.6 on 2025-09-28 05:45

import django.core.validators
import ecommerce.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_paper_options_remove_paper_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='pdf_file',
            field=models.FileField(default=ecommerce.utils.default_pdf, upload_to='papers/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip'])]),
        ),
    ]
