# Generated by Django 5.2.6 on 2025-09-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='pdf_file',
            new_name='file',
        ),
    ]
