# Generated by Django 5.2.6 on 2025-09-28 10:12

import django.core.validators
import ecommerce.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_rename_pdf_file_syllabus_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadmap',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='is_current',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='category',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='description',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='pdf_guide',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='title',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='university',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='views_count',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='file',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='title',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='university',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='year',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadmap',
            name='pdf_file',
            field=models.FileField(default=ecommerce.utils.default_pdf, upload_to='roadmaps/roadmap/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip'])]),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='pdf_file',
            field=models.FileField(default=ecommerce.utils.default_pdf, upload_to='roadmaps/syllabus/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip'])]),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
