# Generated by Django 5.2.6 on 2025-09-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_coupon'),
    ]

    operations = [
    ]
