# Generated by Django 5.2.6 on 2025-09-27 10:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='note',
            name='year',
        ),
        migrations.AddField(
            model_name='note',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='university.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='note',
            name='credit_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(upload_to='notes/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'zip'])]),
        ),
    ]
