# Generated by Django 5.2.6 on 2025-09-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_note_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='branch',
        ),
    ]
