# Generated by Django 5.2.6 on 2025-09-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_remove_note_exam_type_and_more'),
        ('papers', '0002_alter_paper_options_remove_paper_subject_and_more'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
